(define (with-draw balance)
	(define (pull amount)
		(if (<= amount balance)
			(begin (set! balance (- balance amount)) 
				balance)
			"not enough money!"))
	(define (push amount)
		(begin (set! balance (+ balance amount)) 
		balance)
		)
	(define (dispatch command)
		(cond ((eq? command 'pull) pull)
		      ((eq? command 'push) push)
		      (else "unknow command")	))
	dispatch)
